### ISSUE TITLE
script_graph_classification.py can't run

### ISSUE THREAD

**Issue by wangzeyu135798** [jwzhanggy/SEG-BERT#3]
**script_graph_classification.py can't run
in code/MethodBertComp.py line 112, weight_embeds = self.raw_feature_embeddings(weight)
RuntimeError: size mismatch, m1: [6760 x 40], m2: [28 x 32] at **..\aten\src\TH/generic/THTensorMath.cpp:41****

**Comment by jwzhanggy** [comment]
Fixed. Please download the new code and try it again.

I update the scripts, graph-bert components as well as the result folder. In the ./result/Padding/ folder, I added 3 subfolders for storing the pre-processed data with different strategies. 

The reported error in your comments is caused by running the "full_input" strategy based on the pre-processed data according to the "isolated_segment" strategy. So, there is a mismatch of the variable sizes. Just FYI.
